### ISSUE TITLE
UI automation test using Playwright

### ISSUE THREAD

**Issue by depapp** [bearmentor/bearmentor#7]
Since this awesome project doesn't have any UI integration tests, I would like to propose adding one using [Playwright](https://playwright.dev)

**Comment by mhaidarhanif** [comment]
Thanks @depapp for the suggestion. Playwright will be used very later on once the key functionalities are settled.

@zainfathoni (from @bearmentor/team of collaborators) has more experience on this than me, so will be handled by him better.

**Comment by zainfathoni** [comment]
To get started with it, could you please write the test scenarios in the [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development) format once you have settled with a few scenarios, @mhaidarhanif?

**Comment by mhaidarhanif** [comment]
@zainfathoni Alright, we'll do after most critical scenarios are settled

I think the most basic one right now is just the login flow

**Comment by depapp** [comment]
@mhaidarhanif @zainfathoni can I raise a PR related to e2e integration test?

```javascript
  test("user should be able to see mentors list", async () => {
    await homePage.goToMentorsPage()
    await expect(mentorsPage.mentorListName).toContainText([
      `Maya Asmara`,
      `Thoriq Nur Faizal`,
      `Muhammad Haekal`,
    ])
  })
```

https://github.com/bearmentor/bearmentor/assets/6134774/fa81f847-da8e-4f1f-b327-0cb4704d3fce

**Comment by mhaidarhanif** [comment]
@depapp It's possible. Can you use the seed data of users and filter them, instead of hard coding the user names in the test?

**Comment by zainfathoni** [comment]
And please also use [Page Object Models](http://playwright.dev/docs/pom) abstraction to simplify the test scenarios.
You may look at this example on how to set them up.

https://github.com/zainfathoni/senar.ai/tree/main/e2e/pages
